[profile.default]
evm_version = "prague"
bytecode_hash = "none"
cbor_metadata = false
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'cache_forge'
no_match_test = 'testCounter'
gas_reports = ["*"]
gas_reports_ignore = ["TestToken", "TestCounter"]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@oz-v5.4.0/=lib/oz-v5.4.0/contracts/",
    "account-abstraction/=lib/account-abstraction/contracts/",
    "@account-abstraction-v8/=lib/account-abstractionV8/contracts",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "forge-std/=lib/forge-std/src/",
    "hardhat/=node_modules/hardhat/",
    "erc6551/=lib/erc6551/",
    "solady/=lib/solady/src",
]

# default
always_use_create_2_factory = true
via-ir = true
optimizer = true
optimizer_runs = 200
